#!/usr/bin/env bash
# a Bash script to transfer a file from our client to a server

if [ $# -eq 4 ]
then
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":
else
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USER_NAME PATH_TO_SSH_KEY"
fi
