#!/usr/bin/env bash
# a Bash script that installs nginx and configure it

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
