#!/usr/bin/env bash
# Fix a webserver to run Nginx as nginx user on Port 8080

# set a user in the config by replacing "#user"
sed -i "s/#usr www-data/user nginx/" /etc/nginx/nginx.conf

# Replace port 80 with 8080 in sites available
sed -i "s/80/8080/g" /etc/nginx/sites-available/defualt

# Give read & write permissions
chmod 644 /etc/nginx/nginx.conf

# restart nginx with new user "nginx"
sudo -u nginx service nginx restart
